;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-change
        evil-delete-backward-char-and-join
        evil-forward-char
        evil-inner-tag
        evil-insert
        evil-next-line
        evil-normal-state
        evil-set-marker
        evil-window-middle
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        evil-forward-word-begin
        evil-previous-line
        evil-search-next
        ))
